[workspace]
members = ["milli", "filter-parser", "http-ui", "benchmarks", "infos", "helpers", "cli"]
default-members = ["milli"]

[profile.dev]
opt-level = 3

[profile.release]
debug = true

# Make sure that the build scripts and proc-macros are compiled with
# all the optimizations. It speeds up the zip crate that we use in the build.rs.
[profile.dev.build-override]
opt-level = 3
[profile.release.build-override]
opt-level = 3
[profile.bench.build-override]
opt-level = 3
[profile.test.build-override]
opt-level = 3

[patch.crates-io]
fst = { git = "https://github.com/MarinPostma/fst.git", rev = "e6c606b7507e8cb5e502d1609f9b909b8690bac5" }
